//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadsideService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrderDetails
    {
        public int DetailID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ServiceID { get; set; }
    
        public virtual ServiceOrders ServiceOrders { get; set; }
        public virtual Services Services { get; set; }
    }
}
